// Generates a clean invoice PDF using a hidden print window.
// No external libraries — uses the browser's native print-to-PDF.

export function generateInvoicePDF(data) {
  const { number, date, client, profile, lineItems, total, periodLabel } = data

  const fmtMoney = (n) => `$${Number(n).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
  const fmtDate = (d) => new Date(d + 'T12:00:00').toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const rows = lineItems.map(li => `
    <tr>
      <td style="padding:10px 8px;border-bottom:1px solid #eee;">${li.description}</td>
      <td style="padding:10px 8px;border-bottom:1px solid #eee;text-align:right;">${li.hours.toFixed(2)}</td>
      <td style="padding:10px 8px;border-bottom:1px solid #eee;text-align:right;">${fmtMoney(li.rate)}</td>
      <td style="padding:10px 8px;border-bottom:1px solid #eee;text-align:right;font-weight:600;">${fmtMoney(li.amount)}</td>
    </tr>
  `).join('')

  const totalHours = lineItems.reduce((s, li) => s + li.hours, 0)

  const html = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Invoice ${number}</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: -apple-system, 'Segoe UI', Roboto, sans-serif; color:#1a2540; padding:48px; max-width:780px; margin:0 auto; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; margin-bottom:48px; }
  .invoice-title { font-size:34px; font-weight:700; color:#0D1526; letter-spacing:-0.5px; }
  .invoice-meta { text-align:right; color:#6B7FA0; font-size:13px; line-height:1.7; }
  .invoice-num { font-size:15px; font-weight:600; color:#1a2540; }
  .parties { display:flex; justify-content:space-between; margin-bottom:40px; gap:40px; }
  .party { flex:1; }
  .party-label { font-size:11px; text-transform:uppercase; letter-spacing:1px; color:#9BA5BB; font-weight:600; margin-bottom:8px; }
  .party-name { font-size:16px; font-weight:600; margin-bottom:4px; }
  .party-detail { font-size:13px; color:#6B7FA0; line-height:1.6; white-space:pre-line; }
  table { width:100%; border-collapse:collapse; margin-bottom:24px; }
  th { font-size:11px; text-transform:uppercase; letter-spacing:0.5px; color:#9BA5BB; font-weight:600; text-align:left; padding:0 8px 12px; border-bottom:2px solid #1a2540; }
  th.right { text-align:right; }
  .totals { display:flex; justify-content:flex-end; margin-top:8px; }
  .totals-box { width:280px; }
  .total-row { display:flex; justify-content:space-between; padding:8px 8px; font-size:14px; color:#6B7FA0; }
  .total-row.grand { border-top:2px solid #1a2540; margin-top:8px; padding-top:14px; font-size:20px; font-weight:700; color:#0D1526; }
  .accent { color:#C47D0E; }
  .footer { margin-top:56px; padding-top:24px; border-top:1px solid #eee; font-size:12px; color:#9BA5BB; text-align:center; }
  @media print { body { padding:24px; } }
</style>
</head>
<body>
  <div class="header">
    <div>
      <div class="invoice-title">INVOICE</div>
      <div style="color:#C47D0E;font-weight:600;margin-top:4px;">${profile.businessName || 'Your Business'}</div>
    </div>
    <div class="invoice-meta">
      <div class="invoice-num">#${number}</div>
      <div>${fmtDate(date)}</div>
      <div>${periodLabel}</div>
    </div>
  </div>

  <div class="parties">
    <div class="party">
      <div class="party-label">From</div>
      <div class="party-name">${profile.businessName || '—'}</div>
      <div class="party-detail">${profile.businessEmail || ''}${profile.businessAddress ? '\n' + profile.businessAddress : ''}</div>
    </div>
    <div class="party">
      <div class="party-label">Bill To</div>
      <div class="party-name">${client}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th class="right">Hours</th>
        <th class="right">Rate</th>
        <th class="right">Amount</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="totals">
    <div class="totals-box">
      <div class="total-row"><span>Total Hours</span><span>${totalHours.toFixed(2)}</span></div>
      <div class="total-row grand"><span>Total Due</span><span class="accent">${fmtMoney(total)}</span></div>
    </div>
  </div>

  <div class="footer">
    Thank you for your business · Generated by SprintHQ
  </div>

  <script>
    window.onload = function() { window.print(); }
  </script>
</body>
</html>`

  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
  } else {
    alert('Please allow popups to generate the invoice PDF.')
  }
}
